### PR TITLE
Fix misuses of input iterators in BoundedVector

### LINKED ISSUE #486: BoundedVector misuses InputIterators
Input iterators are single pass, meaning once you've incremented them, they're gone. That means functions like [this](https://github.com/ros2/rosidl/blob/afff057f283959d33da065349eb971b8b3653170/rosidl_runtime_cpp/include/rosidl_runtime_cpp/bounded_vector.hpp#L283) are broken for input iterators. The call to `distance(first, last)` will consume the entire range, and then `assign(first, last)` will do nothing.

```
#include <sstream>
#include <iterator>
#include <cassert>
#include <rosidl_runtime_cpp/bounded_vector.hpp>
int main()
{
  std::istringstream s("1 2 3");
  BoundedVector<int> b;
  std::istream_iterator<int> iter(s), end;
  b.assign(iter, s);
  assert(b.size() == 3);
}
```
You should either change that function to only accept forward iterators, or use tag dispatching to select different functions depending on `std::iterator_traits<InputIterator>::iterator_category`. For input iterators you could just do something like:

```
Base::clear();
while (first != last)
  push_back(*first++);
```
For forward iterators you can use `std::distance(first, last)` safely.

### PR DESCRIPTION
**Pull request by jwakely**
Input iterators are single pass, so calling std::distance(first, last)
will consume the input and leave [first,last) as an empty range.

This change makes assign(InputIterator, InputIterator) and
insert(const_iterator, InputIterator, InputIterator) dispatch to
overloaded functions that choose the right overload based on the
iterator category. For forward iterators the original implementation is
used. For input iterators assign will construct a new vector and if that
doesn't throw, use swap to replace the contents of *this. For insert
each value is inserted at the end and if the bound is not exceeded
std::rotate is used to shift them to the desired position, otherwise the
inserted elements are removed from the end before the function exits.

This retains the strong exception safety guarantee for both operations,
so that exceeding the bound does not alter the existing contents of the
vector.

Fixes #486

Signed-off-by: Jonathan Wakely <github@kayari.org>

### CODE REVIEW

File: rosidl_runtime_cpp/include/rosidl_runtime_cpp/bounded_vector.hpp [hunk 1]
```diff
@@ -640,6 +640,71 @@ class BoundedVector
...
+    typename Base::const_iterator position,
+    InputIterator first,
+    InputIterator last,
+    std::input_iterator_tag)
+  {
+    const auto orig_size = size();
+    const auto idx = position - cbegin();
+    try {
+      while (first != last)
+        push_back(*first++);
```
Comment (hidmic) [inline rosidl_runtime_cpp/include/rosidl_runtime_cpp/bounded_vector.hpp:682]: @jwakely nit: use braces for this `while` statement's block

Comment (jwakely) [reply rosidl_runtime_cpp/include/rosidl_runtime_cpp/bounded_vector.hpp:682]: Fixed and force-pushed.

**Comment by jwakely** [comment]
I've added some unit test and re-pushed.

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp [hunk 2]
```diff
@@ -50,3 +52,39 @@ TEST(rosidl_generator_cpp, bounded_vector_rvalue) {
   ASSERT_EQ(vv[0], 1);
   ASSERT_EQ(vv[1], 2);
 }
+
+TEST(rosidl_generator_cpp, bounded_vector_comparisons) {
+  rosidl_runtime_cpp::BoundedVector<int, 2> v;
+  ASSERT_EQ(v, v);
+  const decltype(v) vv;
```
Comment (hidmic) [inline rosidl_runtime_cpp/test/test_bounded_vector.cpp:59]: @jwakely why not 

```c++
  rosidl_runtime_cpp::BoundedVector<int, 2> v, vv;
```

above? It's a tiny bit clearer.

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp [hunk 3]
```diff
@@ -50,3 +52,39 @@ TEST(rosidl_generator_cpp, bounded_vector_rvalue) {
...
+  ASSERT_GT(v, vv);
+  ASSERT_LT(vv, v);
+}
+
+TEST(rosidl_generator_cpp, bounded_vector_input_iterators) {
+  rosidl_runtime_cpp::BoundedVector<int, 4> v;
+  std::istringstream ss("1 2 3");
+  std::istream_iterator<int> ii(ss), end;
+  v.assign(ii, end);
+  ASSERT_EQ(v.size(), 3);
```
Comment (hidmic) [inline rosidl_runtime_cpp/test/test_bounded_vector.cpp:71]: @jwakely checking `v`'s content would also be good. Same elsewhere.

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp [hunk 4]
```diff
@@ -50,3 +52,39 @@ TEST(rosidl_generator_cpp, bounded_vector_rvalue) {
...
+  ss.clear();
+  ss.str("10 11 12 13 14 15");
+  ii == ss;
```
Comment (hidmic) [inline rosidl_runtime_cpp/test/test_bounded_vector.cpp:74]: @jwakely `ii` equals `ss`?  I lost you here.

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp (hunk 2 above)
Comment (jwakely) [reply rosidl_runtime_cpp/test/test_bounded_vector.cpp:59]: I was just copying what was already on line 49.

Comment (jwakely) [reply rosidl_runtime_cpp/test/test_bounded_vector.cpp:59]: If you don't like that style, you should probably change the existing tests so people don't try to be consistent with them.

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp (hunk 3 above)
Comment (jwakely) [reply rosidl_runtime_cpp/test/test_bounded_vector.cpp]: Done

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp (hunk 4 above)
Comment (jwakely) [reply rosidl_runtime_cpp/test/test_bounded_vector.cpp]: Gah, it should be `ii = ss`. It happens to work because the iterator still refers to that stream anyway, but it should be `ii = ss`. Fixed now.

File: rosidl_runtime_cpp/test/test_bounded_vector.cpp (hunk 2 above)
Comment (hidmic) [reply rosidl_runtime_cpp/test/test_bounded_vector.cpp]: Hmm, I see. Not happy with either, but fine to leave as-is.

**Comment by jwakely** [comment]
Yes. You were always missing such a test :stuck_out_tongue:

**Comment by jwakely** [comment]
The new unit test (which is testing existing functionality) is triggering a new warning, which was always present but didn't warn because you weren't testing those member functions. At some point I'm going to point out it's your code that was broken, and missing unit tests, and there's a limit to how much time I'm prepared to spend being a good samaritan on a project I have no personal interest in.

**Comment by jwakely** [comment]
Tests green again, including the tests added for the existing functionality and for the part I fixed.

**Comment by sloretz** [comment]
@hidmic @jwakely friendly ping :) Looks like this one needs a rebase

**Comment by hidmic** [comment]
@jwakely I'll go ahead and do the rebase. Hope you don't mind.

**Comment by jwakely** [comment]
Please feel free. I hadn't noticed it had bitrotted.

**Comment by jwakely** [comment]
The conflict was caused by #444 which is ... odd. Defending against completely bogus code like trying to insert `end(), begin()` seems unnecessary, and the new test has undefined behaviour, see https://github.com/ros2/rosidl/pull/444/files#r442387420

You should have merged my pull request before it got invalidated by that :wink:

**Comment by hidmic** [comment]
No worries, if it's UB it has to be fixed one way or another.

**Comment by hidmic** [comment]
Sanity check up to `rosidl_runtime_cpp`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11205/)

**Comment by hidmic** [comment]
Since you reviewed #444, mind to take a look @dirk-thomas ?

**Comment by hidmic** [comment]
Alright, CI's green. Thank you again for pushing this @jwakely!
